spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mappers/*.xml
server:
  port: 8000

